### ISSUE TITLE
Explore the data

### ISSUE THREAD

**Issue by Lyublyana** [course-dprep/Start_of_Academic_Year_relationship_with_AirBnB_Market#7]
- select the days we are interested in calendar, turn that into data frame
- for listings; add columns/variables we're interested in to calendar data frame by using id
--> variables: Professional host, room type
                       (need to calculate superhost dummy for some cities)
- summary statistics of data frame
- plot variable of interest from data frame

Deliverables:
-Above as R-code and with output

**Comment by karlijns** [comment]
I'm just going to start with doing this for Amsterdam, then we can run the same code for the other cities and see what we have to change for each dataset if there are differences.
